name       : la-capitaine-icon-theme
version    : 0.6.2
release    : 7
source     :
    - https://github.com/keeferrourke/la-capitaine-icon-theme/archive/v0.6.2.tar.gz : e63e4bc97a7bbf4db71f17fa3b1c71086e3ed8b1dc44b4d10f95d97aa7db2c9d
homepage   : https://krourke.org/projects/art/la-capitaine-icon-theme
license    :
    - GPL-3.0-or-later
    - MIT
component  : desktop.theme
summary    : La Capitaine is an icon pack inspired by macOS and Google's Material Design
description: |
    The set of icons takes inspiration from the latest iterations of macOS and Google's Material Design through the use of visually pleasing gradients, shadowing, and simple icon geometry.
setup      : |
    %patch < $pkgfiles/0001-Don-t-require-prompts.patch
    ./configure
    rm {*.md,configure,COPYING,LICENSE}
install    : |
    install -dm00644 $installdir/usr/share/icons/la-capitaine-icon-theme
    mv * $installdir/usr/share/icons/la-capitaine-icon-theme/
    chmod -R 00644 $installdir/usr/share/icons/la-capitaine-icon-theme/*
